version: '3.3'
services:
  postgres:
    image: postgres:13.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: dudow
      POSTGRES_DB: thomows
    ports:
      - 5432:5432
